id: PCE6B55C3
initial_creation_type: input
source_metadata:
  title: Guru Drakpo Series
  language: zh
  description: 'Texts related to Guru Drakpo (gu ru drag po), the wrathful manifestation
    of Guru Padmasambhava, in all his various forms:'
  volume:
    28e8c96f1e9442998d286a15bf684ce2:
      title: Wrathful Guru Mantra Visualization
      parent: Mantra Visualization
    a1f1944c56ab4223931d363246910b32:
      title: Daily Practice of Guru Drakpo
      parent: Sādhanas
created_at: '2022-03-01T03:44:35.620158'
last_modified_at: '2022-03-01T03:44:35.620161'
